projects/not-a-forge/config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token

  # Public pages
  root "pages#home"

  # Registration routes
  get "signup", to: "registrations#new", as: :signup
  post "signup", to: "registrations#create"

  # Dashboard
  resources :repositories

  # Settings namespace
  namespace :settings do
    resource :profile, only: [ :show, :edit, :update, :destroy ]
    resources :tokens
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

projects/not-a-forge/app/views/shared/_navigation.html.erb
<header class="page-header">
  <nav>
    <h2>Main</h2>
    <ul>
      <li><%= link_to "Home", root_path %></li>
    </ul>
  </nav>

  <% if authenticated? %>
    <nav>
      <h2>Account</h2>
      <ul>
        <li><%= link_to "Dashboard", repositories_path %></li>
        <li><%= link_to "Settings", settings_profile_path %></li>
        <li><%= link_to "Sign Out", session_path, data: { turbo_method: :delete } %></li>
      </ul>
    </nav>
  <% else %>
    <nav>
      <h2>Account</h2>
      <ul>
        <li><%= link_to "Sign In", new_session_path %></li>
        <li><%= link_to "Sign Up", signup_path %></li>
      </ul>
    </nav>
  <% end %>

  <%= yield %>
</header>

projects/not-a-forge/app/views/shared/_side_bar.html.erb
<aside class="side-bar">
  <nav>
    <b>Hi <%= Current.user.email_address %></b>
    <ul>
      <li><%= link_to "Settings", settings_profile_path %></li>
      <li><%= link_to "Sign Out", session_path, data: { turbo_method: :delete } %></li>
    </ul>
  </nav>

  <%= content_for?(:side_bar) ? yield(:side_bar) : nil %>
</aside>

projects/not-a-forge/app/views/shared/_top_bar.html.erb
<header class="top-bar">
    <%= link_to "Not a forge", root_path %>
    <%= content_for?(:top_bar) ? yield(:top_bar) : nil %>
</header>