projects/sherman-deploy/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root 'pages#home'
  get 'dashboard', to: 'pages#dashboard'

  resource :session
  resource :registration, only: [:new, :create]
  resources :passwords, param: :token
  
  resources :sources do
    resources :service_locations do
      member do
        post :upload_sources
        post :start_services
      end
    end

    member do
      post :refetch
    end
  end
end

projects/sherman-deploy/app/models/source.rb
class Source < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :git_url, presence: true

  has_many :service_locations, dependent: :destroy

  after_create :fetch_source_later

  def fetched?
    last_fetched_at.present? && git.initialized?
  end

  def git
    Git.new(directory: source_directory, git_url:)
  end

  def fetch_source_later
    ProcessLater.perform_later(self, :fetch_source)
  end

  def fetch_source
    puts "Fetching source #{name}"

    if git.initialized?
      puts "Pulling source #{name}"
      git.pull
    else
      puts "Cloning source #{name}"
      git.clone
    end

    touch(:last_fetched_at)
    puts "Source #{name} fetched at #{last_fetched_at}"
  end

  def checkout_directory
    source_directory.join("checkout")
  end

  def source_directory
    sources_directory = Rails.application.config.sources_directory
    source_directory = sources_directory.join(name)
    FileUtils.mkdir_p(source_directory)
    source_directory
  end
end

projects/sherman-deploy/app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: [:show, :edit, :update, :destroy, :refetch]

  def index
    @sources = Source.all
  end

  def show
  end

  def new
    @source = Source.new
  end

  def create
    @source = Source.new(source_params)

    if @source.save
      redirect_to @source, notice: "Source was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @source.update(source_params)
      redirect_to @source, notice: "Source was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @source.destroy
    redirect_to sources_path, notice: "Source was successfully deleted.", status: :see_other
  end

  def refetch
    @source.fetch_source
    redirect_to @source, notice: "Source was successfully refetched."
  end

  private

  def set_source
    @source = Source.find(params[:id])
  end

  def source_params
    params.require(:source).permit(:name, :git_url)
  end
end

projects/sherman-deploy/app/helpers/sources_helper.rb
module SourcesHelper
end

projects/sherman-deploy/app/views/sources/_form.html.erb
<%= form_with(model: source) do |form| %>
  <% if source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(source.errors.count, "error") %> prohibited this source from being saved:</h2>
      <ul>
        <% source.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :git_url %>
    <%= form.text_field :git_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %> 

projects/sherman-deploy/app/views/sources/edit.html.erb
<main>
  <section>
    <h1>Edit Source</h1>

    <%= render 'form', source: @source %>

    <%= link_to 'Show', @source %> |
    <%= link_to 'Back', sources_path %>
  </section>
</main>

projects/sherman-deploy/app/views/sources/index.html.erb
<main>
  <section>
    <h1>Sources</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Git URL</th>
          <th>Last Fetched</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @sources.each do |source| %>
          <tr>
            <td><%= source.name %></td>
            <td><%= source.git_url %></td>
            <td><%= source.last_fetched_at ? time_ago_in_words(source.last_fetched_at) + " ago" : "Never" %></td>
            <td><%= link_to "Show", source %></td>
            <td><%= link_to "Edit", edit_source_path(source) %></td>
            <td><%= link_to "Delete", source, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to "New Source", new_source_path %>
  </section>
</main>

projects/sherman-deploy/app/views/sources/new.html.erb
<main>
  <section>
    <h1>New Source</h1>

    <%= render 'form', source: @source %>

    <%= link_to 'Back', sources_path %>
  </section>
</main>

projects/sherman-deploy/app/views/sources/show.html.erb
<main>
  <section>
    <h1><%= @source.name %></h1>

    <p>
      <strong>Git URL:</strong>
      <%= @source.git_url %>
    </p>

    <p>
      <strong>Last Fetched:</strong>
      <%= @source.last_fetched_at ? time_ago_in_words(@source.last_fetched_at) + " ago" : "Never" %>
    </p>

    <div>
      <%= link_to "Edit", edit_source_path(@source) %> |
      <%= link_to "Back", sources_path %> |
      <%= link_to "Refetch", refetch_source_path(@source), data: { turbo_method: :post } %>
    </div>
  </section>

  <section>
    <h2>Service Locations</h2>
    <p>
      Service locations are paths to folders inside this source's repository that contain services
      that can be deployed.
    </p>

    <% if @source.service_locations.any? %>
      <ul>
        <% @source.service_locations.each do |location| %>
          <li>
            <%= location.name %> (<%= location.path %>) 
            <% unless location.exist? %>
              Not found
            <% end %>
            - 
            <%= link_to "Details", source_service_location_path(@source, location) %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>No service locations defined yet.</p>
    <% end %>

    <p>
      <%= link_to "Manage Service Locations", source_service_locations_path(@source) %>
    </p>
  </section>
</main>